import type { Donor, Hospital, AmbulanceDriver, EmergencyHospital } from '@/types';

export const BLOOD_GROUPS = ['A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-'];
export const ORGAN_TYPES = ['Kidney', 'Liver', 'Heart', 'Cornea', 'Lungs', 'Bone Marrow'];
export const CITIES = ['Mumbai', 'Pune', 'Nagpur'];

// Mock Donors - 15+ donors across multiple blood groups and cities
export const mockDonors: Donor[] = [
  {
    id: 'donor_1',
    user_id: null,
    email: 'donor1@gmail.com',
    full_name: 'Rajesh Kumar',
    age: 28,
    blood_group: 'O+',
    city: 'Mumbai',
    phone: '9876543210',
    organs: ['Kidney', 'Liver', 'Cornea'],
    emergency_contact: '9876543211',
    consent: true,
    available: true,
    donor_level: 'Silver',
    donor_points: 250,
    blood_donations: 3,
    medical_allergies: 'Penicillin',
    medical_conditions: '',
    lat: 19.0760,
    lng: 72.8777,
    created_at: new Date('2024-01-15').toISOString(),
  },
  {
    id: 'donor_2',
    user_id: null,
    email: 'donor2@gmail.com',
    full_name: 'Priya Sharma',
    age: 32,
    blood_group: 'A+',
    city: 'Mumbai',
    phone: '9876543220',
    organs: ['Kidney', 'Heart', 'Lungs'],
    emergency_contact: '9876543221',
    consent: true,
    available: true,
    donor_level: 'Gold',
    donor_points: 450,
    blood_donations: 5,
    medical_allergies: '',
    medical_conditions: '',
    lat: 19.1136,
    lng: 72.8697,
    created_at: new Date('2023-06-20').toISOString(),
  },
  {
    id: 'donor_3',
    user_id: null,
    email: 'donor3@gmail.com',
    full_name: 'Amit Patel',
    age: 26,
    blood_group: 'B+',
    city: 'Pune',
    phone: '9876543230',
    organs: ['Kidney', 'Liver', 'Bone Marrow'],
    emergency_contact: '9876543231',
    consent: true,
    available: true,
    donor_level: 'Bronze',
    donor_points: 100,
    blood_donations: 1,
    medical_allergies: 'Sulfa',
    medical_conditions: '',
    lat: 18.5204,
    lng: 73.8567,
    created_at: new Date('2024-08-10').toISOString(),
  },
  {
    id: 'donor_4',
    user_id: null,
    email: 'donor4@gmail.com',
    full_name: 'Neha Singh',
    age: 24,
    blood_group: 'O-',
    city: 'Pune',
    phone: '9876543240',
    organs: ['Kidney', 'Liver', 'Heart', 'Cornea', 'Lungs', 'Bone Marrow'],
    emergency_contact: '9876543241',
    consent: true,
    available: true,
    donor_level: 'Platinum Lifesaver',
    donor_points: 800,
    blood_donations: 12,
    medical_allergies: '',
    medical_conditions: '',
    lat: 18.5312,
    lng: 73.8445,
    created_at: new Date('2022-03-05').toISOString(),
  },
  {
    id: 'donor_5',
    user_id: null,
    email: 'donor5@gmail.com',
    full_name: 'Vikram Das',
    age: 35,
    blood_group: 'AB+',
    city: 'Mumbai',
    phone: '9876543250',
    organs: ['Kidney', 'Liver'],
    emergency_contact: '9876543251',
    consent: true,
    available: false,
    donor_level: 'Silver',
    donor_points: 220,
    blood_donations: 4,
    medical_allergies: '',
    medical_conditions: 'Hypertension (controlled)',
    lat: 19.0176,
    lng: 72.8479,
    created_at: new Date('2023-11-12').toISOString(),
  },
  {
    id: 'donor_6',
    user_id: null,
    email: 'donor6@gmail.com',
    full_name: 'Ananya Gupta',
    age: 29,
    blood_group: 'B-',
    city: 'Nagpur',
    phone: '9876543260',
    organs: ['Kidney', 'Cornea', 'Bone Marrow'],
    emergency_contact: '9876543261',
    consent: true,
    available: true,
    donor_level: 'Gold',
    donor_points: 550,
    blood_donations: 6,
    medical_allergies: 'Aspirin',
    medical_conditions: '',
    lat: 21.1458,
    lng: 79.0882,
    created_at: new Date('2023-02-28').toISOString(),
  },
  {
    id: 'donor_7',
    user_id: null,
    email: 'donor7@gmail.com',
    full_name: 'Ravi Menon',
    age: 31,
    blood_group: 'A-',
    city: 'Pune',
    phone: '9876543270',
    organs: ['Kidney', 'Liver', 'Heart'],
    emergency_contact: '9876543271',
    consent: true,
    available: true,
    donor_level: 'Silver',
    donor_points: 300,
    blood_donations: 3,
    medical_allergies: '',
    medical_conditions: '',
    lat: 18.5089,
    lng: 73.8256,
    created_at: new Date('2024-04-19').toISOString(),
  },
  {
    id: 'donor_8',
    user_id: null,
    email: 'donor8@gmail.com',
    full_name: 'Deepa Reddy',
    age: 27,
    blood_group: 'O+',
    city: 'Nagpur',
    phone: '9876543280',
    organs: ['Kidney', 'Liver', 'Cornea', 'Bone Marrow'],
    emergency_contact: '9876543281',
    consent: true,
    available: true,
    donor_level: 'Gold',
    donor_points: 480,
    blood_donations: 8,
    medical_allergies: '',
    medical_conditions: '',
    lat: 21.1215,
    lng: 79.0562,
    created_at: new Date('2023-09-03').toISOString(),
  },
  {
    id: 'donor_9',
    user_id: null,
    email: 'donor9@gmail.com',
    full_name: 'Sanjay Iyer',
    age: 33,
    blood_group: 'AB-',
    city: 'Mumbai',
    phone: '9876543290',
    organs: ['Liver', 'Heart'],
    emergency_contact: '9876543291',
    consent: true,
    available: true,
    donor_level: 'Bronze',
    donor_points: 150,
    blood_donations: 2,
    medical_allergies: '',
    medical_conditions: '',
    lat: 19.0825,
    lng: 72.8812,
    created_at: new Date('2024-07-22').toISOString(),
  },
  {
    id: 'donor_10',
    user_id: null,
    email: 'donor10@gmail.com',
    full_name: 'Kavya Nair',
    age: 25,
    blood_group: 'B+',
    city: 'Mumbai',
    phone: '9876543300',
    organs: ['Kidney', 'Liver', 'Lungs', 'Bone Marrow'],
    emergency_contact: '9876543301',
    consent: true,
    available: true,
    donor_level: 'Gold',
    donor_points: 420,
    blood_donations: 7,
    medical_allergies: '',
    medical_conditions: '',
    lat: 19.1808,
    lng: 72.9694,
    created_at: new Date('2023-05-14').toISOString(),
  },
  {
    id: 'donor_11',
    user_id: null,
    email: 'donor11@gmail.com',
    full_name: 'Arjun Verma',
    age: 30,
    blood_group: 'O+',
    city: 'Pune',
    phone: '9876543310',
    organs: ['Kidney', 'Heart', 'Cornea'],
    emergency_contact: '9876543311',
    consent: true,
    available: true,
    donor_level: 'Silver',
    donor_points: 280,
    blood_donations: 4,
    medical_allergies: 'Latex',
    medical_conditions: '',
    lat: 18.5642,
    lng: 73.7769,
    created_at: new Date('2024-02-08').toISOString(),
  },
  {
    id: 'donor_12',
    user_id: null,
    email: 'donor12@gmail.com',
    full_name: 'Swati Desai',
    age: 28,
    blood_group: 'A+',
    city: 'Nagpur',
    phone: '9876543320',
    organs: ['Kidney', 'Liver', 'Bone Marrow'],
    emergency_contact: '9876543321',
    consent: true,
    available: true,
    donor_level: 'Gold',
    donor_points: 500,
    blood_donations: 9,
    medical_allergies: '',
    medical_conditions: '',
    lat: 21.1610,
    lng: 79.0620,
    created_at: new Date('2023-07-17').toISOString(),
  },
  {
    id: 'donor_13',
    user_id: null,
    email: 'donor13@gmail.com',
    full_name: 'Mohit Kumar',
    age: 26,
    blood_group: 'B-',
    city: 'Mumbai',
    phone: '9876543330',
    organs: ['Kidney', 'Liver'],
    emergency_contact: '9876543331',
    consent: true,
    available: true,
    donor_level: 'Bronze',
    donor_points: 120,
    blood_donations: 1,
    medical_allergies: '',
    medical_conditions: '',
    lat: 19.1678,
    lng: 72.8526,
    created_at: new Date('2024-08-25').toISOString(),
  },
  {
    id: 'donor_14',
    user_id: null,
    email: 'donor14@gmail.com',
    full_name: 'Priyanka Chopra',
    age: 34,
    blood_group: 'O+',
    city: 'Pune',
    phone: '9876543340',
    organs: ['Kidney', 'Heart', 'Lungs'],
    emergency_contact: '9876543341',
    consent: true,
    available: true,
    donor_level: 'Silver',
    donor_points: 320,
    blood_donations: 5,
    medical_allergies: '',
    medical_conditions: '',
    lat: 18.5018,
    lng: 73.8636,
    created_at: new Date('2023-12-01').toISOString(),
  },
  {
    id: 'donor_15',
    user_id: null,
    email: 'donor15@gmail.com',
    full_name: 'Akshay Bhat',
    age: 29,
    blood_group: 'AB+',
    city: 'Mumbai',
    phone: '9876543350',
    organs: ['Liver', 'Heart', 'Bone Marrow'],
    emergency_contact: '9876543351',
    consent: true,
    available: true,
    donor_level: 'Gold',
    donor_points: 460,
    blood_donations: 7,
    medical_allergies: '',
    medical_conditions: '',
    lat: 19.1344,
    lng: 72.9193,
    created_at: new Date('2023-10-09').toISOString(),
  },
];

// Mock Hospitals - Maharashtra Focus (Mumbai, Pune, Nagpur)
export const mockHospitals: Hospital[] = [
  {
    id: 'hospital_1',
    user_id: null,
    email: 'kem.mumbai@aarogyam.org',
    hospital_name: 'KEM Hospital & Trauma Center Mumbai',
    registration_id: 'REG-001-MUM',
    city: 'Mumbai',
    address: 'Acharya Donde Marg, Parel, Mumbai',
    contact_person: 'Dr. Pravin R. Kulkarni',
    phone: '9820154310',
    verified: true,
    lat: 19.0028,
    lng: 72.8427,
    inventory: {
      'O+': 18,
      'O-': 8,
      'A+': 14,
      'B+': 12,
      'AB+': 6,
      'Kidney': 4,
      'Liver': 2,
      'Heart': 1,
    },
    created_at: new Date('2020-01-15').toISOString(),
  },
  {
    id: 'hospital_2',
    user_id: null,
    email: 'sassoon.pune@aarogyam.org',
    hospital_name: 'Sassoon General Hospital Pune',
    registration_id: 'REG-002-PUN',
    city: 'Pune',
    address: 'Near Pune Railway Station, Sassoon Road, Pune',
    contact_person: 'Dr. Sunita Deshmukh',
    phone: '9822354311',
    verified: true,
    lat: 18.5284,
    lng: 73.8739,
    inventory: {
      'O+': 15,
      'O-': 6,
      'A+': 10,
      'B+': 11,
      'AB+': 4,
      'Kidney': 3,
      'Liver': 2,
      'Heart': 1,
    },
    created_at: new Date('2020-06-20').toISOString(),
  },
  {
    id: 'hospital_3',
    user_id: null,
    email: 'gmc.nagpur@aarogyam.org',
    hospital_name: 'Government Medical College (GMC) Nagpur',
    registration_id: 'REG-003-NAG',
    city: 'Nagpur',
    address: 'Medical Square, Hanuman Nagar, Nagpur',
    contact_person: 'Dr. Arvind Raut',
    phone: '9823054312',
    verified: true,
    lat: 21.1278,
    lng: 79.0982,
    inventory: {
      'O+': 12,
      'O-': 5,
      'A+': 9,
      'B+': 8,
      'AB+': 3,
      'Kidney': 2,
      'Liver': 1,
      'Heart': 0,
    },
    created_at: new Date('2021-03-10').toISOString(),
  },
  {
    id: 'hospital_4',
    user_id: null,
    email: 'lilavati.mumbai@aarogyam.org',
    hospital_name: 'Lilavati Hospital & Research Centre',
    registration_id: 'REG-004-MUM',
    city: 'Mumbai',
    address: 'A-791, Bandra Reclamation, Bandra West, Mumbai',
    contact_person: 'Dr. Rohan Mehta',
    phone: '9820554313',
    verified: true,
    lat: 19.0514,
    lng: 72.8295,
    inventory: {
      'O+': 14,
      'O-': 7,
      'A+': 11,
      'B+': 9,
      'AB+': 5,
      'Kidney': 3,
      'Liver': 2,
      'Heart': 2,
    },
    created_at: new Date('2021-08-15').toISOString(),
  },
  {
    id: 'hospital_5',
    user_id: null,
    email: 'rubyhall.pune@aarogyam.org',
    hospital_name: 'Ruby Hall Clinic Pune',
    registration_id: 'REG-005-PUN',
    city: 'Pune',
    address: '40, Sassoon Road, Sangamvadi, Pune',
    contact_person: 'Dr. Manisha Shinde',
    phone: '9822754314',
    verified: true,
    lat: 18.5323,
    lng: 73.8785,
    inventory: {
      'O+': 16,
      'O-': 6,
      'A+': 13,
      'B+': 10,
      'AB+': 4,
      'Kidney': 4,
      'Liver': 2,
      'Heart': 1,
    },
    created_at: new Date('2021-11-20').toISOString(),
  },
  {
    id: 'hospital_6',
    user_id: null,
    email: 'kingsway.nagpur@aarogyam.org',
    hospital_name: 'Kingsway Hospitals Nagpur',
    registration_id: 'REG-006-NAG',
    city: 'Nagpur',
    address: '44, Kingsway Road, Near Kasturchand Park, Nagpur',
    contact_person: 'Dr. Ajay Agrawal',
    phone: '9067375860',
    verified: true,
    lat: 21.1550,
    lng: 79.0880,
    inventory: {
      'O+': 15,
      'O-': 6,
      'A+': 10,
      'B+': 12,
      'AB+': 4,
      'Kidney': 3,
      'Liver': 2,
      'Heart': 1,
    },
    created_at: new Date('2022-01-10').toISOString(),
  },
];

// Registered Ambulance Services Fleet (Dummy Dataset of 8 drivers with capacities & pricing)
export const AMBULANCE_SERVICES: AmbulanceDriver[] = [
  {
    id: 'amb_1',
    driver_name: 'Suresh Patil',
    phone: '+91 98201 22345',
    city: 'Mumbai',
    vehicle_no: 'MH-01-EA-4521',
    capacity_type: 'Large Capacity (ICU / Ventilator)',
    equipment: ['Advanced Cardiac Life Support (ACLS)', 'Transport Ventilator', 'Defibrillator', 'Multi-para Monitor'],
    price_inr: 1200,
    base_rate_info: '₹1,200 base fee (incl. first 5km + ALS paramedic crew)',
    rating: 4.9,
    trips_completed: 432,
    reach_time_minutes: 6,
    distance_km: 2.1,
    available: true,
    lat: 19.0620,
    lng: 72.8340,
  },
  {
    id: 'amb_2',
    driver_name: 'Ganesh Shinde',
    phone: '+91 98202 33456',
    city: 'Mumbai',
    vehicle_no: 'MH-02-BQ-8910',
    capacity_type: 'Small Capacity (Basic Life Support)',
    equipment: ['Oxygen Cylinder', 'Spine Board & Collar', 'First Aid Trauma Kit', 'Stretcher Trolley'],
    price_inr: 650,
    base_rate_info: '₹650 base fee (incl. first 5km + Emergency EMT)',
    rating: 4.8,
    trips_completed: 289,
    reach_time_minutes: 8,
    distance_km: 3.4,
    available: true,
    lat: 19.0112,
    lng: 72.8450,
  },
  {
    id: 'amb_3',
    driver_name: 'Nitin Pawar',
    phone: '+91 98203 44567',
    city: 'Mumbai',
    vehicle_no: 'MH-03-TR-2341',
    capacity_type: 'Large Capacity (ICU / Ventilator)',
    equipment: ['Invasive Ventilator', 'Syringe Infusion Pumps', 'Suction Machine', 'Emergency Resuscitation Bag'],
    price_inr: 1350,
    base_rate_info: '₹1,350 base fee (Specialized Critical Care Team on board)',
    rating: 5.0,
    trips_completed: 512,
    reach_time_minutes: 11,
    distance_km: 4.8,
    available: true,
    lat: 19.1150,
    lng: 72.8680,
  },
  {
    id: 'amb_4',
    driver_name: 'Sachin Jadhav',
    phone: '+91 98221 55678',
    city: 'Pune',
    vehicle_no: 'MH-12-RN-7782',
    capacity_type: 'Large Capacity (ICU / Ventilator)',
    equipment: ['ICU Ventilator', 'Cardiac Defibrillator', 'Suction Unit', 'Oxygen Concentrator'],
    price_inr: 1100,
    base_rate_info: '₹1,100 base fee (Critical Care Ambulance with Paramedic)',
    rating: 4.9,
    trips_completed: 374,
    reach_time_minutes: 5,
    distance_km: 1.8,
    available: true,
    lat: 18.5230,
    lng: 73.8590,
  },
  {
    id: 'amb_5',
    driver_name: 'Ramesh Gaikwad',
    phone: '+91 98222 66789',
    city: 'Pune',
    vehicle_no: 'MH-14-GH-3329',
    capacity_type: 'Small Capacity (Basic Life Support)',
    equipment: ['High-flow Oxygen Delivery', 'Emergency Immobilizers', 'Pulse Oximeter', 'Stretcher'],
    price_inr: 600,
    base_rate_info: '₹600 base fee (Rapid Emergency Transit)',
    rating: 4.7,
    trips_completed: 198,
    reach_time_minutes: 7,
    distance_km: 2.9,
    available: true,
    lat: 18.5350,
    lng: 73.8710,
  },
  {
    id: 'amb_6',
    driver_name: 'Anand Kadam',
    phone: '+91 98223 77890',
    city: 'Pune',
    vehicle_no: 'MH-12-EM-9941',
    capacity_type: 'Large Capacity (ICU / Ventilator)',
    equipment: ['Pediatric & Adult Ventilator', 'Defibrillator', 'Emergency Drug Cart', 'Vital Monitor'],
    price_inr: 1250,
    base_rate_info: '₹1,250 base fee (Full Mobile Intensive Care)',
    rating: 4.9,
    trips_completed: 460,
    reach_time_minutes: 9,
    distance_km: 3.7,
    available: true,
    lat: 18.5110,
    lng: 73.8420,
  },
  {
    id: 'amb_7',
    driver_name: 'Manoj Wankhede (Nagpur Emergency)',
    phone: '9067375860',
    city: 'Nagpur',
    vehicle_no: 'MH-31-CB-1122',
    capacity_type: 'Large Capacity (ICU / Ventilator)',
    equipment: ['Transport Ventilator', 'External Pacemaker', 'Multi-lead ECG', 'Oxygen Bank'],
    price_inr: 1050,
    base_rate_info: '₹1,050 base fee (ICU On-Wheels with Nurse)',
    rating: 4.9,
    trips_completed: 310,
    reach_time_minutes: 6,
    distance_km: 2.3,
    available: true,
    lat: 21.1410,
    lng: 79.0820,
  },
  {
    id: 'amb_8',
    driver_name: 'Dinesh Meshram (Nagpur Quick Aid)',
    phone: '8530779934',
    city: 'Nagpur',
    vehicle_no: 'MH-40-AZ-5561',
    capacity_type: 'Small Capacity (Basic Life Support)',
    equipment: ['Oxygen Cylinders', 'Trauma Splints', 'First Aid Station', 'Ambu Bag'],
    price_inr: 500,
    base_rate_info: '₹500 base fee (Rapid Triage Transport)',
    rating: 4.8,
    trips_completed: 245,
    reach_time_minutes: 8,
    distance_km: 3.1,
    available: true,
    lat: 21.1320,
    lng: 79.0910,
  },
];

// Emergency Hospitals dataset: Government & Private with real-time beds, doctors, and location tracking
export const EMERGENCY_HOSPITALS: EmergencyHospital[] = [
  // --- MUMBAI GOVERNMENT ---
  {
    id: 'gov_mum_1',
    name: 'KEM Hospital & Seth G.S. Medical College',
    type: 'Government',
    city: 'Mumbai',
    address: 'Acharya Donde Marg, Parel, Mumbai, Maharashtra 400012',
    phone: '+91 22 2410 7000',
    emergency_helpline: '108 / 022-24107000',
    reach_time_minutes: 7,
    distance_km: 2.4,
    lat: 19.0028,
    lng: 72.8427,
    beds: {
      icu_total: 45,
      icu_available: 8,
      trauma_total: 30,
      trauma_available: 6,
      general_emergency_total: 80,
      general_emergency_available: 19,
    },
    doctors: [
      { name: 'Dr. Pravin Kulkarni', role: 'Head of Trauma Surgery', specialization: 'Trauma & Ortho Surgery', on_duty: true },
      { name: 'Dr. Sunita Rao', role: 'Emergency Physician', specialization: 'Critical Care Triage', on_duty: true },
      { name: 'Dr. Anand Joshi', role: 'Neurosurgeon on Duty', specialization: 'Emergency Neurosurgery', on_duty: true },
    ],
    facilities: ['24/7 Level-1 Trauma Bay', 'Emergency OT ready', 'In-house Blood Bank', 'CT/MRI Triage Unit'],
    cost_tier: 'Free / Subsidized',
    google_maps_url: 'https://www.google.com/maps/dir/?api=1&destination=KEM+Hospital+Parel+Mumbai',
  },
  {
    id: 'gov_mum_2',
    name: 'Lokmanya Tilak Municipal General Hospital (Sion)',
    type: 'Government',
    city: 'Mumbai',
    address: 'Sion West, Mumbai, Maharashtra 400022',
    phone: '+91 22 2407 6381',
    emergency_helpline: '022-24063000',
    reach_time_minutes: 12,
    distance_km: 4.8,
    lat: 19.0360,
    lng: 72.8600,
    beds: {
      icu_total: 38,
      icu_available: 5,
      trauma_total: 25,
      trauma_available: 4,
      general_emergency_total: 70,
      general_emergency_available: 14,
    },
    doctors: [
      { name: 'Dr. Deepak Naik', role: 'Chief Medical Officer', specialization: 'Emergency Medicine', on_duty: true },
      { name: 'Dr. Varsha Sawant', role: 'Senior Trauma Surgeon', specialization: 'General & Vascular Surgery', on_duty: true },
    ],
    facilities: ['24x7 Ambulance Bay', 'Organ Harvest Ready', 'Dedicated Burn & Trauma Ward', 'Direct Triage Desk'],
    cost_tier: 'Free / Subsidized',
    google_maps_url: 'https://www.google.com/maps/dir/?api=1&destination=Sion+Hospital+Mumbai',
  },
  // --- MUMBAI PRIVATE ---
  {
    id: 'pvt_mum_1',
    name: 'Lilavati Hospital and Research Centre',
    type: 'Private',
    city: 'Mumbai',
    address: 'A-791, Bandra Reclamation, Bandra West, Mumbai, Maharashtra 400050',
    phone: '+91 22 2675 1000',
    emergency_helpline: '022-26568000',
    reach_time_minutes: 9,
    distance_km: 3.2,
    lat: 19.0514,
    lng: 72.8295,
    beds: {
      icu_total: 35,
      icu_available: 11,
      trauma_total: 18,
      trauma_available: 7,
      general_emergency_total: 40,
      general_emergency_available: 16,
    },
    doctors: [
      { name: 'Dr. Rohan Mehta', role: 'Director of Critical Care', specialization: 'Emergency Resuscitation', on_duty: true },
      { name: 'Dr. Ananya Sen', role: 'Cardiac Surgeon', specialization: 'Emergency Angioplasty & Bypass', on_duty: true },
      { name: 'Dr. Vikram Malhotra', role: 'Consultant Ortho', specialization: 'Polytrauma Management', on_duty: true },
    ],
    facilities: ['Cath Lab 24/7', 'Green Corridor Organ Transit', 'Helipad Access', 'Advanced Robotic Surgery OT'],
    cost_tier: 'Premium Super-Specialty',
    google_maps_url: 'https://www.google.com/maps/dir/?api=1&destination=Lilavati+Hospital+Bandra+Mumbai',
  },
  {
    id: 'pvt_mum_2',
    name: 'Kokilaben Dhirubhai Ambani Hospital',
    type: 'Private',
    city: 'Mumbai',
    address: 'Rao Saheb, Achutrao Patwardhan Marg, Four Bungalows, Andheri West, Mumbai',
    phone: '+91 22 4269 6969',
    emergency_helpline: '022-42699999',
    reach_time_minutes: 15,
    distance_km: 6.5,
    lat: 19.1311,
    lng: 72.8252,
    beds: {
      icu_total: 50,
      icu_available: 14,
      trauma_total: 22,
      trauma_available: 9,
      general_emergency_total: 60,
      general_emergency_available: 21,
    },
    doctors: [
      { name: 'Dr. Sameer Godbole', role: 'Head Emergency Med', specialization: 'Emergency Critical Care', on_duty: true },
      { name: 'Dr. Rashmi Kapoor', role: 'Neurosurgeon', specialization: 'Brain & Spine Trauma', on_duty: true },
    ],
    facilities: ['Level-1 Multi-Specialty Trauma', 'Full Extracorporeal Membrane Oxygenation (ECMO)', 'Blood Bank 24/7'],
    cost_tier: 'Premium Super-Specialty',
    google_maps_url: 'https://www.google.com/maps/dir/?api=1&destination=Kokilaben+Hospital+Andheri+Mumbai',
  },

  // --- PUNE GOVERNMENT ---
  {
    id: 'gov_pun_1',
    name: 'Sassoon General Hospital & B.J. Govt Medical College',
    type: 'Government',
    city: 'Pune',
    address: 'Station Road, Near Pune Railway Station, Sangamvadi, Pune 411001',
    phone: '+91 20 2612 8000',
    emergency_helpline: '108 / 020-26128000',
    reach_time_minutes: 6,
    distance_km: 2.0,
    lat: 18.5284,
    lng: 73.8739,
    beds: {
      icu_total: 40,
      icu_available: 7,
      trauma_total: 28,
      trauma_available: 5,
      general_emergency_total: 75,
      general_emergency_available: 22,
    },
    doctors: [
      { name: 'Dr. Sunita Deshmukh', role: 'HOD Emergency Dept', specialization: 'Trauma & Emergency Care', on_duty: true },
      { name: 'Dr. Mahesh Bhosale', role: 'General Surgeon', specialization: 'Acute Trauma Surgery', on_duty: true },
    ],
    facilities: ['24-Hour Casualty & Emergency OT', 'Civil Blood Storage', 'Free Meds & Surgery for Accident Victims'],
    cost_tier: 'Free / Subsidized',
    google_maps_url: 'https://www.google.com/maps/dir/?api=1&destination=Sassoon+General+Hospital+Pune',
  },

  // --- PUNE PRIVATE ---
  {
    id: 'pvt_pun_1',
    name: 'Ruby Hall Clinic Pune',
    type: 'Private',
    city: 'Pune',
    address: '40, Sassoon Road, Sangamvadi, Pune 411001',
    phone: '+91 20 6645 5100',
    emergency_helpline: '020-26163391',
    reach_time_minutes: 8,
    distance_km: 2.8,
    lat: 18.5323,
    lng: 73.8785,
    beds: {
      icu_total: 32,
      icu_available: 9,
      trauma_total: 16,
      trauma_available: 6,
      general_emergency_total: 45,
      general_emergency_available: 18,
    },
    doctors: [
      { name: 'Dr. Manisha Shinde', role: 'Chief of Trauma Unit', specialization: 'Critical Care & Ortho Trauma', on_duty: true },
      { name: 'Dr. Rahul Patil', role: 'Interventional Cardiologist', specialization: 'Emergency Cardiac Care', on_duty: true },
    ],
    facilities: ['Accredited Stroke & Chest Pain Unit', '24x7 Ambulance Hotline', 'Digital X-Ray & Immediate CT Scan'],
    cost_tier: 'Standard Private',
    google_maps_url: 'https://www.google.com/maps/dir/?api=1&destination=Ruby+Hall+Clinic+Pune',
  },

  // --- NAGPUR GOVERNMENT ---
  {
    id: 'gov_nag_1',
    name: 'Government Medical College & Hospital (GMC) Nagpur',
    type: 'Government',
    city: 'Nagpur',
    address: 'Medical Square, Hanuman Nagar, Nagpur, Maharashtra 440009',
    phone: '+91 712 274 4400',
    emergency_helpline: '108 / 0712-2744400',
    reach_time_minutes: 8,
    distance_km: 2.7,
    lat: 21.1278,
    lng: 79.0982,
    beds: {
      icu_total: 36,
      icu_available: 8,
      trauma_total: 24,
      trauma_available: 6,
      general_emergency_total: 65,
      general_emergency_available: 17,
    },
    doctors: [
      { name: 'Dr. Arvind Raut', role: 'Emergency Medical Director', specialization: 'Trauma & Disaster Management', on_duty: true },
      { name: 'Dr. Sneha Borkar', role: 'Senior Resident Surgeon', specialization: 'Acute Triage & Resuscitation', on_duty: true },
    ],
    facilities: ['Dedicated Central India Trauma Center', '24/7 Red Cross Blood Bank Access', 'Subsidized Emergency Care'],
    cost_tier: 'Free / Subsidized',
    google_maps_url: 'https://www.google.com/maps/dir/?api=1&destination=Government+Medical+College+Nagpur',
  },

  // --- NAGPUR PRIVATE ---
  {
    id: 'pvt_nag_1',
    name: 'Kingsway Hospitals Nagpur',
    type: 'Private',
    city: 'Nagpur',
    address: '44, Kingsway Road, Near Kasturchand Park, Nagpur 440001',
    phone: '+91 712 678 9000',
    emergency_helpline: '0712-6789100',
    reach_time_minutes: 10,
    distance_km: 3.6,
    lat: 21.1550,
    lng: 79.0880,
    beds: {
      icu_total: 28,
      icu_available: 10,
      trauma_total: 14,
      trauma_available: 5,
      general_emergency_total: 35,
      general_emergency_available: 12,
    },
    doctors: [
      { name: 'Dr. Ajay Agrawal', role: 'Trauma Care Specialist', specialization: 'Polytrauma & Emergency Med', on_duty: true },
      { name: 'Dr. Meena Muley', role: 'Intensivist', specialization: 'Advanced Critical Care', on_duty: true },
    ],
    facilities: ['Ultramodern Critical Care Wing', 'Rapid Response Ambulance Dispatch', 'On-site MRI & Angiography'],
    cost_tier: 'Standard Private',
    google_maps_url: 'https://www.google.com/maps/dir/?api=1&destination=Kingsway+Hospitals+Nagpur',
  },
];

// Stats for landing page
export const LANDING_STATS = {
  lives_saved: 1420,
  active_donors: 16800,
  hospitals_connected: 185,
  cities_covered: 3,
};

// Testimonials
export const TESTIMONIALS = [
  {
    name: 'Rajesh Patil',
    role: 'Accident Survivor & Recipient',
    city: 'Mumbai',
    message: 'Aarogyam saved my life after a highway collision. The helper clicked Emergency on the landing page, ambulance reached in 7 minutes, and KEM prepped the trauma bay before arrival.',
    image: '👨‍⚕️',
  },
  {
    name: 'Priya Shinde',
    role: 'Verified Blood Donor',
    city: 'Pune',
    message: 'Being part of Aarogyam in Pune gives me purpose. I received an urgent O- alert for an accident victim at Sassoon Hospital and was able to reach in time.',
    image: '👩‍⚕️',
  },
  {
    name: 'Dr. Pravin Kulkarni',
    role: 'Trauma Unit Head, Mumbai',
    city: 'Mumbai',
    message: 'The instant accident alert trigger is revolutionary. When bystanders alert us with live ETA and bed reservations, our emergency OT is sterilized and waiting.',
    image: '👨‍💼',
  },
];

