import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'hi' | 'mr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Brand & Taglines
    'app.name': 'JeevanSetu',
    'app.tagline': 'Connecting People, Saving lives',
    'app.hero_badge': 'Real-Time Blood Bank Inventory, Emergency Routing & Anti-Fraud Network',
    'app.hero_title_1': 'Connecting People,',
    'app.hero_title_2': 'Saving lives in Real Time',
    'app.hero_desc': 'Real-time stock tracking by blood group with expiry alerts, race-safe last-unit allocation, ABO/Rh compatibility & distance routing, donor verification, and fraud prevention.',

    
    // Emergency Button & Actions
    'emergency.btn': 'EMERGENCY',
    'emergency.accident_btn': 'ACCIDENT EMERGENCY',
    'emergency.subtitle': 'Instant Help - No Login Required',
    'emergency.modal_title': '🚨 Aarogyam Emergency Accident Response',
    'emergency.modal_desc': 'Select immediate assistance. Real-time direct dispatch and bed reservation with zero login delay.',
    'emergency.tab_ambulance': 'Direct Ambulance Call',
    'emergency.tab_private': 'Nearby Private Hospitals',
    'emergency.tab_government': 'Nearby Govt Hospitals',
    'emergency.call_now': 'Call Ambulance Now',
    'emergency.call_helpline': 'Emergency Call 108',
    'emergency.filter_city': 'City Location:',
    'emergency.capacity': 'Vehicle Capacity',
    'emergency.fare': 'Standard Fare',
    'emergency.eta': 'Estimated Reach Time',
    'emergency.beds_available': 'Emergency Beds Available',
    'emergency.icu_beds': 'ICU Beds',
    'emergency.trauma_beds': 'Trauma Beds',
    'emergency.gen_beds': 'General Beds',
    'emergency.doctors_on_duty': 'Specialist Doctors on Duty',
    'emergency.maps_directions': 'Open Google Maps Navigation',
    'emergency.trigger_hospital': 'Trigger Emergency Alert to Hospital',
    'emergency.alert_sent_title': '🚨 Hospital Alert Triggered in Real Time!',
    'emergency.alert_sent_desc': 'Emergency Bay Alerted. Emergency Token generated. Trauma staff & on-call doctors have been notified to prepare the emergency OT and beds.',
    'emergency.token': 'Emergency Token ID',
    'emergency.status': 'Dispatch Status',
    'emergency.status_val': 'Trauma Bay Prepped & Awaiting Patient',
    'emergency.back': 'Back to Services',
    'emergency.close': 'Close Window',

    // Navigation & Roles
    'nav.register_donor': 'Register Donor',
    'nav.hospital_access': 'Hospital Access',
    'nav.login_signup': 'Login / Sign Up',
    'nav.dashboard': 'Dashboard',
    'nav.pledge_organ': 'Pledge Organ',
    'nav.ai_insights': 'AI Insights & Blogs',
    'nav.my_report': 'My Report',
    'nav.donor_directory': 'Donor Directory',
    'nav.nearby_hospitals': 'Nearby Hospitals',
    'nav.transparency_log': 'Transparency Log',
    'nav.sign_out': 'Sign Out',
    'nav.emergency_request': 'EMERGENCY REQUEST',

    // Landing Page Sections
    'landing.emergency_callout_title': 'Accident or Critical Emergency?',
    'landing.emergency_callout_desc': 'Seconds save lives. Direct ambulance dispatch and instant bed/doctor reservation across Mumbai, Pune, and Nagpur.',
    'landing.how_it_works': 'How Aarogyam Works',
    'landing.step1_title': 'Register or Trigger',
    'landing.step1_desc': 'Emergency accident assistance is 1-click on the landing page. Donors and hospitals register verified credentials.',
    'landing.step2_title': 'Instant AI & Location Tracking',
    'landing.step2_desc': 'Locate closest ambulances and government/private hospitals with live doctor and ICU bed counts.',
    'landing.step3_title': 'Real-Time Lifesaving Prep',
    'landing.step3_desc': 'Real-time alert informs hospital emergency rooms to prepare trauma bay and blood units before arrival.',
    'landing.stats_lives': 'Lives Saved',
    'landing.stats_donors': 'Active Donors',
    'landing.stats_hospitals': 'Connected Hospitals',
    'landing.stats_cities': 'Cities Covered',
    'landing.testimonials_title': 'Stories of Life Saved in Maharashtra',
    'landing.cta_title': 'Be a Lifesaver Today',
    'landing.cta_desc': 'Every second counts. Register as a donor, connect your hospital, or keep Aarogyam ready for roadside emergencies.',
    'landing.cta_btn_donor': 'Register as Life Donor',
    'landing.cta_btn_hospital': 'Connect Hospital Network',

    // Auth Page
    'auth.welcome_back': 'Welcome Back',
    'auth.join_aarogyam': 'Join the Aarogyam Network',
    'auth.sign_in': 'Sign In',
    'auth.register': 'Register',
    'auth.role_individual': 'Individual Donor',
    'auth.role_hospital': 'Hospital / Medical Center',
    'auth.city_select': 'Select City (Maharashtra)',
    'auth.email': 'Email Address',
    'auth.password': 'Password',
    'auth.full_name': 'Full Name',
    'auth.phone': 'Phone Number',
    'auth.blood_group': 'Blood Group',
    'auth.hospital_name': 'Hospital Name',
    'auth.registration_id': 'Medical Registration ID',
    'auth.address': 'Complete Hospital Address',
    'auth.contact_person': 'Medical Superintendent / Contact Person',
    'auth.submit_signin': 'Sign In to Account',
    'auth.submit_register': 'Complete Registration',

    // Common
    'common.language': 'Language',
    'common.english': 'English',
    'common.hindi': 'हिन्दी',
    'common.marathi': 'मराठी',
    'common.mumbai': 'Mumbai',
    'common.pune': 'Pune',
    'common.nagpur': 'Nagpur',
    'common.government': 'Government',
    'common.private': 'Private',
    'common.rating': 'Rating',
    'common.available': 'Available',
    'common.occupied': 'Occupied',
    'common.minutes': 'mins',
    'common.km': 'km',

    // Hospital Dashboard
    'hospital.dashboard_title': 'Hospital Portal',
    'hospital.active_requests': 'Active Requests',
    'hospital.fulfilled_month': 'Fulfilled This Month',
    'hospital.avg_match_time': 'Average Match Time',
    'hospital.donor_pool_size': 'City Donor Pool Size',
    'hospital.create_emergency': 'Create Emergency Request',
    'hospital.trigger_matching': 'Trigger Matching Engine',
    'hospital.trigger_matching_desc': 'Initiate emergency donor compatibility search',
    'hospital.connect_donors': 'Connect with Donors',
    'hospital.connect_donors_desc': 'See available blood and posthumous organ pledges',
    'hospital.search_stock': 'Search Nearby Hospital Stock',
    'hospital.search_stock_desc': 'Request cross-center organ or blood transfers',
    'hospital.active_past_requests': 'Active & Past Emergency Requests',
    'hospital.requests_subtitle': 'Real-time status tracking with direct matching engine and dispatch access',
    'hospital.type': 'Type',
    'hospital.required_item': 'Required Item',
    'hospital.urgency': 'Urgency',
    'hospital.city': 'City',
    'hospital.match_score': 'Match Score',
    'hospital.status': 'Status',
    'hospital.action': 'Action',
    'hospital.match_now': 'Match Now',
    'hospital.track_dispatch': 'Track Dispatch',
    'hospital.hash_log': 'Hash Log',
    'hospital.verified': 'Verified',
    'hospital.license': 'License',
    'hospital.emergency_alert_title': 'CRITICAL INCOMING CASUALTY ALERT',
    'hospital.emergency_alert_sub': 'Bystander reported accident victims en route. Prepare Trauma Bay immediately.',
    'hospital.patients_allocated': 'Victims Allocated',
    'hospital.eta': 'Estimated Arrival',
    'hospital.acknowledge': 'Acknowledge & Ready Trauma Bay',
    'hospital.mark_arrived': 'Mark Victims Received',

    // Donor Dashboard
    'donor.portal': 'Active Donor Portal',
    'donor.welcome': 'Welcome back',
    'donor.subtitle': 'Track your life-saving impact, donor rank, and readiness for emergencies.',
    'donor.tab_overview': 'Impact Overview',
    'donor.tab_leaderboard': 'City Leaderboard',
    'donor.tab_notifications': 'Match Feed',
    'donor.blood_group': 'Blood Group',
    'donor.city_zone': 'City Zone',
    'donor.pledged_organs': 'Pledged Organs',
    'donor.blood_donations': 'Blood Donations',
    'donor.phone': 'Phone',
    'donor.availability': 'Emergency Availability',
    'donor.availability_ready': 'Ready for emergency alerts',
    'donor.availability_paused': 'Temporarily paused',
    'donor.pledge_organs_action': 'Pledge Organs',
    'donor.pledge_organs_desc': 'Update organs willing to donate (+60 pts)',
    'donor.log_donation_action': 'Log Blood Donation',
    'donor.log_donation_desc': 'Record a donation event (+30 pts)',
    'donor.progression': 'Lifesaver Progression',
    'donor.lifetime_points': 'Lifetime Points',
    'donor.badges_title': 'Earned & Unlockable Badges',
    'donor.badges_desc': 'Collect milestone badges by pledging and donating regularly',
    'donor.total_points': 'Total Points',
    'donor.donations': 'Donations',
    'donor.organs_pledged': 'Organs Pledged',
    'donor.top_donors': 'Top Donors',
    'donor.leaderboard_desc': 'Live rankings based on donation frequency and organ pledges',
    'donor.alerts_title': 'Alerts & Match History',
    'donor.alerts_desc': 'Live notifications when your blood or organs match a hospital request',
    'donor.no_alerts': 'No notifications yet',

    // Multi-Patient Emergency Allocation
    'emergency.num_patients': 'Number of Accident Victims / Patients',
    'emergency.num_patients_hint': 'Auto-distributes patients across nearby hospitals if trauma beds fill up',
    'emergency.allocation_title': 'Bed Distribution & Ambulance Dispatch',
    'emergency.primary_hosp': 'Primary Hospital (Direct Bay)',
    'emergency.secondary_hosp': 'Nearby Secondary Hospital (Capacity Reroute)',
    'emergency.patients_count': 'Patients',
    'emergency.reroute_notice': 'Trauma capacity reached at primary center. Remaining patients are automatically routed to nearest hospital.',
  },

  hi: {
    // Brand & Taglines
    'app.name': 'जीवनसेतु',
    'app.tagline': 'Connecting People, Saving lives',
    'app.hero_badge': 'रीयल-टाइम ब्लड बैंक इन्वेंट्री, आपातकालीन रूटिंग एवं एंटी-फ्रॉड नेटवर्क',
    'app.hero_title_1': 'Connecting People,',
    'app.hero_title_2': 'Saving lives (जीवन रक्षा नेटवर्क)',
    'app.hero_desc': 'ब्लड ग्रुप वार रीयल-टाइम स्टॉक, समाप्ति चेतावनी, अंतिम यूनिट का सुरक्षित आवंटन, संगतता एवं दूरी आधारित रूटिंग तथा दाता सत्यापन।',


    // Emergency Button & Actions
    'emergency.btn': 'आपातकाल (EMERGENCY)',
    'emergency.accident_btn': 'दुर्घटना आपातकाल सेवा',
    'emergency.subtitle': 'तुरंत सहायता - बिना लॉगिन के उपलब्ध',
    'emergency.modal_title': '🚨 आरोग्यम् त्वरित दुर्घटना आपातकालीन सहायता',
    'emergency.modal_desc': 'तुरंत सहायता चुनें। बिना लॉगिन के सीधे एम्बुलेंस बुलाएं अथवा निकटतम अस्पताल में इमरजेंसी बेड व डॉक्टर अलर्ट भेजें।',
    'emergency.tab_ambulance': 'सीधी एम्बुलेंस कॉल',
    'emergency.tab_private': 'निकटतम निजी अस्पताल',
    'emergency.tab_government': 'निकटतम सरकारी अस्पताल',
    'emergency.call_now': 'तुरंत एम्बुलेंस को कॉल करें',
    'emergency.call_helpline': 'आपातकालीन हेल्पलाइन 108',
    'emergency.filter_city': 'शहर चुनें:',
    'emergency.capacity': 'वाहन क्षमता व सुविधा',
    'emergency.fare': 'मानक किराया',
    'emergency.eta': 'पहुंचने का अनुमानित समय',
    'emergency.beds_available': 'उपलब्ध आपातकालीन बेड',
    'emergency.icu_beds': 'आईसीयू बेड',
    'emergency.trauma_beds': 'ट्रॉमा बेड',
    'emergency.gen_beds': 'सामान्य बेड',
    'emergency.doctors_on_duty': 'ड्यूटी पर विशेषज्ञ डॉक्टर',
    'emergency.maps_directions': 'गूगल मैप्स नेविगेशन खोलें',
    'emergency.trigger_hospital': 'अस्पताल को तुरंत आपातकालीन अलर्ट भेजें',
    'emergency.alert_sent_title': '🚨 अस्पताल को रियल-टाइम अलर्ट भेजा गया!',
    'emergency.alert_sent_desc': 'इमरजेंसी वार्ड अलर्ट हो चुका है। आपातकालीन टोकन जारी किया गया है। मरीज के पहुंचने से पहले ऑपरेशन थियेटर और बेड तैयार किए जा रहे हैं।',
    'emergency.token': 'इमरजेंसी टोकन आईडी',
    'emergency.status': 'तैयारी की स्थिति',
    'emergency.status_val': 'ट्रॉमा वार्ड तैयार - डॉक्टर प्रतीक्षारत',
    'emergency.back': 'वापस सेवाओं पर जाएं',
    'emergency.close': 'खिड़की बंद करें',

    // Navigation & Roles
    'nav.register_donor': 'रक्त/अंग दाता पंजीकरण',
    'nav.hospital_access': 'अस्पताल पोर्टल',
    'nav.login_signup': 'लॉगिन / साइन अप',
    'nav.dashboard': 'डैशबोर्ड',
    'nav.pledge_organ': 'अंगदान संकल्प',
    'nav.ai_insights': 'एआई विश्लेषण व ब्लॉग',
    'nav.my_report': 'मेरी योगदान रिपोर्ट',
    'nav.donor_directory': 'दाता सूची',
    'nav.nearby_hospitals': 'निकटवर्ती अस्पताल',
    'nav.transparency_log': 'पारदर्शिता लॉग',
    'nav.sign_out': 'लॉगआउट',
    'nav.emergency_request': 'आपातकालीन मांग',

    // Landing Page Sections
    'landing.emergency_callout_title': 'सड़क दुर्घटना या गंभीर आपातकाल?',
    'landing.emergency_callout_desc': 'हर सेकंड कीमती है। बिना लॉगिन के सीधे एम्बुलेंस बुलाएं और मुंबई, पुणे व नागपुर के अस्पतालों में बेड व डॉक्टर सुरक्षित करें।',
    'landing.how_it_works': 'आरोग्यम् कैसे काम करता है',
    'landing.step1_title': 'पंजीकरण या आपातकालीन ट्रिगर',
    'landing.step1_desc': 'दुर्घटना के समय होमपेज से 1-क्लिक में तुरंत मदद। दाता और अस्पताल सत्यापित पहचान के साथ जुड़ते हैं।',
    'landing.step2_title': 'तुरंत एआई और स्थान ट्रैकिंग',
    'landing.step2_desc': 'निकटतम एम्बुलेंस और सरकारी/निजी अस्पतालों में उपलब्ध डॉक्टर और आईसीयू बेड तुरंत खोजें।',
    'landing.step3_title': 'वास्तविक समय में जीवन रक्षा',
    'landing.step3_desc': 'अस्पताल को सीधे चेतावनी संदेश जाता है ताकि मरीज के पहुंचने से पहले ट्रॉमा बे और रक्त तैयार मिले।',
    'landing.stats_lives': 'बचाई गई जानें',
    'landing.stats_donors': 'सक्रिय दाता',
    'landing.stats_hospitals': 'संबद्ध अस्पताल',
    'landing.stats_cities': 'कवर किए गए शहर',
    'landing.testimonials_title': 'महाराष्ट्र में जीवन रक्षा की सच्ची कहानियां',
    'landing.cta_title': 'आज ही जीवनदाता बनें',
    'landing.cta_desc': 'एक फैसला किसी की जान बचा सकता है। दाता बनें अथवा दुर्घटना सहायता के लिए आरोग्यम् का उपयोग करें।',
    'landing.cta_btn_donor': 'दाता के रूप में पंजीकरण करें',
    'landing.cta_btn_hospital': 'अस्पताल को नेटवर्क से जोड़ें',

    // Auth Page
    'auth.welcome_back': 'पुनः स्वागत है',
    'auth.join_aarogyam': 'आरोग्यम् नेटवर्क से जुड़ें',
    'auth.sign_in': 'साइन इन करें',
    'auth.register': 'नया पंजीकरण',
    'auth.role_individual': 'व्यक्तिगत दाता',
    'auth.role_hospital': 'अस्पताल / चिकित्सा केंद्र',
    'auth.city_select': 'शहर चुनें (महाराष्ट्र)',
    'auth.email': 'ईमेल पता',
    'auth.password': 'पासवर्ड',
    'auth.full_name': 'पूरा नाम',
    'auth.phone': 'फोन नंबर',
    'auth.blood_group': 'रक्त समूह',
    'auth.hospital_name': 'अस्पताल का नाम',
    'auth.registration_id': 'चिकित्सा पंजीकरण संख्या',
    'auth.address': 'अस्पताल का पूरा पता',
    'auth.contact_person': 'चिकित्सा अधीक्षक / संपर्क व्यक्ति',
    'auth.submit_signin': 'खाते में साइन इन करें',
    'auth.submit_register': 'पंजीकरण पूरा करें',

    // Common
    'common.language': 'भाषा',
    'common.english': 'English',
    'common.hindi': 'हिन्दी',
    'common.marathi': 'मराठी',
    'common.mumbai': 'मुंबई',
    'common.pune': 'पुणे',
    'common.nagpur': 'नागपुर',
    'common.government': 'सरकारी',
    'common.private': 'निजी',
    'common.rating': 'रेटिंग',
    'common.available': 'उपलब्ध',
    'common.occupied': 'व्यस्त',
    'common.minutes': 'मिनट',
    'common.km': 'किमी',

    // Hospital Dashboard
    'hospital.dashboard_title': 'अस्पताल पोर्टल',
    'hospital.active_requests': 'सक्रिय अनुरोध',
    'hospital.fulfilled_month': 'इस माह पूर्ण हुए',
    'hospital.avg_match_time': 'औसत मिलान समय',
    'hospital.donor_pool_size': 'शहर दाता पूल आकार',
    'hospital.create_emergency': 'आपातकालीन मांग दर्ज करें',
    'hospital.trigger_matching': 'दाता मिलान इंजन शुरू करें',
    'hospital.trigger_matching_desc': 'आपातकालीन रक्त/अंग संगतता खोज तुरंत शुरू करें',
    'hospital.connect_donors': 'दाताओं से संपर्क करें',
    'hospital.connect_donors_desc': 'उपलब्ध रक्त एवं पंजीकृत अंगदाताओं की सूची देखें',
    'hospital.search_stock': 'निकटवर्ती अस्पताल स्टॉक खोजें',
    'hospital.search_stock_desc': 'अन्य अस्पतालों से आपातकालीन रक्त या अंग ट्रांसफर मांगें',
    'hospital.active_past_requests': 'सक्रिय एवं पूर्व आपातकालीन अनुरोध',
    'hospital.requests_subtitle': 'वास्तविक समय स्थिति ट्रैकिंग और सीधा प्रेषण नियंत्रण',
    'hospital.type': 'प्रकार',
    'hospital.required_item': 'आवश्यक सामग्री',
    'hospital.urgency': 'प्राथमिकता',
    'hospital.city': 'शहर',
    'hospital.match_score': 'मैच स्कोर',
    'hospital.status': 'स्थिति',
    'hospital.action': 'कार्रवाई',
    'hospital.match_now': 'तुरंत मैच करें',
    'hospital.track_dispatch': 'प्रेषण ट्रैक करें',
    'hospital.hash_log': 'सुरक्षित हैश लॉग',
    'hospital.verified': 'सत्यापित',
    'hospital.license': 'पंजीकरण संख्या',
    'hospital.emergency_alert_title': '🚨 गंभीर आपातकालीन दुर्घटना अलर्ट',
    'hospital.emergency_alert_sub': 'सड़क दुर्घटना के घायल मरीज अस्पताल पहुंच रहे हैं। तुरंत ट्रॉमा बे तैयार करें।',
    'hospital.patients_allocated': 'आवंटित मरीज',
    'hospital.eta': 'अनुमानित आगमन समय',
    'hospital.acknowledge': 'स्वीकार करें व ट्रॉमा बे तैयार करें',
    'hospital.mark_arrived': 'मरीज पहुंच गए (प्राप्त दर्ज करें)',

    // Donor Dashboard
    'donor.portal': 'सक्रिय दाता पोर्टल',
    'donor.welcome': 'पुनः स्वागत है',
    'donor.subtitle': 'अपने जीवनरक्षक योगदान, दाता रैंकिंग और आपातकालीन तैयारी को ट्रैक करें।',
    'donor.tab_overview': 'प्रभाव अवलोकन',
    'donor.tab_leaderboard': 'शहर लीडरबोर्ड',
    'donor.tab_notifications': 'मैच फीड',
    'donor.blood_group': 'रक्त समूह',
    'donor.city_zone': 'शहर क्षेत्र',
    'donor.pledged_organs': 'संकल्पित अंग',
    'donor.blood_donations': 'रक्तदान संख्या',
    'donor.phone': 'फोन',
    'donor.availability': 'आपातकालीन उपलब्धता',
    'donor.availability_ready': 'आपातकाल अलर्ट के लिए तैयार',
    'donor.availability_paused': 'अस्थायी रूप से रोकी गई',
    'donor.pledge_organs_action': 'अंगदान संकल्प लें',
    'donor.pledge_organs_desc': 'दान करने हेतु अंग चुनें (+60 अंक)',
    'donor.log_donation_action': 'रक्तदान दर्ज करें',
    'donor.log_donation_desc': 'किया गया रक्तदान दर्ज करें (+30 अंक)',
    'donor.progression': 'जीवनरक्षक प्रगति',
    'donor.lifetime_points': 'कुल जीवनरक्षक अंक',
    'donor.badges_title': 'अर्जित एवं आगामी बैज',
    'donor.badges_desc': 'नियमित रक्तदान और अंगदान से विशेष बैज प्राप्त करें',
    'donor.total_points': 'कुल अंक',
    'donor.donations': 'दान',
    'donor.organs_pledged': 'संकल्पित अंग',
    'donor.top_donors': 'शीर्ष दाता',
    'donor.leaderboard_desc': 'रक्तदान आवृत्ति और संकल्प के आधार पर वास्तविक रैंकिंग',
    'donor.alerts_title': 'अलर्ट और मिलान इतिहास',
    'donor.alerts_desc': 'जब आपका रक्त या अंग किसी अस्पताल अनुरोध से मेल खाता है तो तुरंत सूचना',
    'donor.no_alerts': 'कोई नया अलर्ट नहीं',

    // Multi-Patient Emergency Allocation
    'emergency.num_patients': 'दुर्घटना पीड़ितों / मरीजों की संख्या',
    'emergency.num_patients_hint': 'बेड भर जाने पर स्वतः निकटतम अस्पताल में मरीज पुनर्निर्देशित होते हैं',
    'emergency.allocation_title': 'मरीज बेड आवंटन एवं एम्बुलेंस प्रेषण',
    'emergency.primary_hosp': 'प्राथमिक अस्पताल (सीधा ट्रॉमा वार्ड)',
    'emergency.secondary_hosp': 'निकटतम द्वितीयक अस्पताल (बेड क्षमता पुनर्निर्देशन)',
    'emergency.patients_count': 'मरीज',
    'emergency.reroute_notice': 'प्राथमिक अस्पताल में ट्रॉमा बेड समाप्त होने के कारण शेष मरीज स्वचालित रूप से नजदीकी अस्पताल को भेजे गए हैं।',
  },

  mr: {
    // Brand & Taglines
    'app.name': 'जीवनसेतू',
    'app.tagline': 'Connecting People, Saving lives',
    'app.hero_badge': 'रिअल-टाइम रक्तपेढी इन्व्हेंटरी, आपत्कालीन रूटिंग व फसवणूक प्रतिबंधक नेटवर्क',
    'app.hero_title_1': 'Connecting People,',
    'app.hero_title_2': 'Saving lives (जीवन रक्षक नेटवर्क)',
    'app.hero_desc': 'रक्तगटनिहाय थेट साठा, मुदत समाप्ती सूचना, शेवटच्या युनिटचे अचूक वाटप, सुसंगतता व अंतरानुसार रूटिंग आणि रक्तदाता पडताळणी.',


    // Emergency Button & Actions
    'emergency.btn': 'आपत्कालीन (EMERGENCY)',
    'emergency.accident_btn': 'अपघात आपत्कालीन मदत',
    'emergency.subtitle': 'त्वरित मदत - लॉगिनची गरज नाही',
    'emergency.modal_title': '🚨 आरोग्यम् अपघात आपत्कालीन प्रतिसाद',
    'emergency.modal_desc': 'तातडीची मदत निवडा. लॉगिनशिवाय थेट रुग्णवाहिका बोलवा किंवा जवळच्या रुग्णालयात बेड व डॉक्टरांना तात्काळ सूचना द्या.',
    'emergency.tab_ambulance': 'थेट रुग्णवाहिका कॉल',
    'emergency.tab_private': 'जवळची खाजगी रुग्णालये',
    'emergency.tab_government': 'जवळची शासकीय रुग्णालये',
    'emergency.call_now': 'आत्ताच रुग्णवाहिकेला कॉल करा',
    'emergency.call_helpline': 'आपत्कालीन हेल्पलाईन १०८',
    'emergency.filter_city': 'शहर निवडा:',
    'emergency.capacity': 'वाहनाची क्षमता व सुविधा',
    'emergency.fare': 'प्रमाणित दर',
    'emergency.eta': 'पोहोचण्याची अंदाजे वेळ',
    'emergency.beds_available': 'उपलब्ध आपत्कालीन खाटा',
    'emergency.icu_beds': 'आयसीयू खाटा',
    'emergency.trauma_beds': 'ट्रॉमा खाटा',
    'emergency.gen_beds': 'सामान्य खाटा',
    'emergency.doctors_on_duty': 'कर्तव्यावर असलेले तज्ज्ञ डॉक्टर',
    'emergency.maps_directions': 'गुगल मॅप्स मार्ग पहा',
    'emergency.trigger_hospital': 'रुग्णालयाला आपत्कालीन सूचना पाठवा',
    'emergency.alert_sent_title': '🚨 रुग्णालयाला थेट सूचना पाठवण्यात आली!',
    'emergency.alert_sent_desc': 'इमर्जन्सी वॉर्ड सतर्क झाला आहे. आपत्कालीन टोकन तयार झाले आहे. रुग्ण पोहोचण्यापूर्वी ट्रॉमा वॉर्ड आणि शस्त्रक्रिया कक्ष सज्ज होत आहे.',
    'emergency.token': 'इमर्जन्सी टोकन आयडी',
    'emergency.status': 'तयारीची स्थिती',
    'emergency.status_val': 'ट्रॉमा वॉर्ड सज्ज - डॉक्टर प्रतीक्षेत',
    'emergency.back': 'मागे सेवांवर जा',
    'emergency.close': 'खिडकी बंद करा',

    // Navigation & Roles
    'nav.register_donor': 'रक्त/अवयव दाता नोंदणी',
    'nav.hospital_access': 'रुग्णालय पोर्टल',
    'nav.login_signup': 'लॉगिन / नोंदणी',
    'nav.dashboard': 'डॅशबोर्ड',
    'nav.pledge_organ': 'अवयवदान संकल्प',
    'nav.ai_insights': 'एआय विश्लेषण व लेख',
    'nav.my_report': 'माझा सहभाग अहवाल',
    'nav.donor_directory': 'दात्यांची यादी',
    'nav.nearby_hospitals': 'जवळची रुग्णालये',
    'nav.transparency_log': 'पारदर्शकता नोंद',
    'nav.sign_out': 'लॉगआउट',
    'nav.emergency_request': 'आपत्कालीन मागणी',

    // Landing Page Sections
    'landing.emergency_callout_title': 'अपघात अथवा गंभीर आणीबाणी?',
    'landing.emergency_callout_desc': 'प्रत्येक सेकंद मोलाचा आहे. लॉगिन न करता थेट रुग्णवाहिका बोलवा आणि मुंबई, पुणे, नागपूरमधील रुग्णालयांमध्ये खाटा व डॉक्टर राखीव करा.',
    'landing.how_it_works': 'आरोग्यम् कसे कार्य करते',
    'landing.step1_title': 'नोंदणी किंवा आपत्कालीन मदत',
    'landing.step1_desc': 'अपघातात मुख्य पानावरून एका क्लिकवर मदत. रक्त/अवयव दाते आणि रुग्णालये अधिकृत नोंदणी करतात.',
    'landing.step2_title': 'त्वरित एआय व स्थान शोध',
    'landing.step2_desc': 'जवळची रुग्णवाहिका तसेच शासकीय/खाजगी रुग्णालयातील उपलब्ध डॉक्टर व आयसीयू खाटा तात्काळ शोधा.',
    'landing.step3_title': 'वेळेवर जीवन रक्षण',
    'landing.step3_desc': 'रुग्णालयाला तत्काळ इशारा जातो, जेणेकरून रुग्ण येण्यापूर्वीच शस्त्रक्रिया कक्ष व रक्त पुरवठा सज्ज राहतो.',
    'landing.stats_lives': 'वाचवलेले प्राण',
    'landing.stats_donors': 'सक्रिय दाते',
    'landing.stats_hospitals': 'संलग्न रुग्णालये',
    'landing.stats_cities': 'समाविष्ट शहरे',
    'landing.testimonials_title': 'महाराष्ट्रातील जीवन रक्षणाच्या सत्यकथा',
    'landing.cta_title': 'आजच जीवनदाता व्हा',
    'landing.cta_desc': 'एक निर्णय कोणाचे तरी प्राण वाचवू शकतो. रक्तदान व अवयवदानासाठी नोंदणी करा किंवा अपघाताच्या वेळी आरोग्यम् वापरा.',
    'landing.cta_btn_donor': 'जीवनदाता म्हणून नोंदणी करा',
    'landing.cta_btn_hospital': 'रुग्णालय नेटवर्कशी जोडा',

    // Auth Page
    'auth.welcome_back': 'पुन्हा स्वागत आहे',
    'auth.join_aarogyam': 'आरोग्यम् परिवारात सामील व्हा',
    'auth.sign_in': 'साइन इन करा',
    'auth.register': 'नवीन नोंदणी',
    'auth.role_individual': 'वैयक्तिक दाता',
    'auth.role_hospital': 'रुग्णालय / वैद्यकीय केंद्र',
    'auth.city_select': 'शहर निवडा (महाराष्ट्र)',
    'auth.email': 'ईमेल पत्ता',
    'auth.password': 'पासवर्ड',
    'auth.full_name': 'संपूर्ण नाव',
    'auth.phone': 'फोन नंबर',
    'auth.blood_group': 'रक्त गट',
    'auth.hospital_name': 'रुग्णालयाचे नाव',
    'auth.registration_id': 'वैद्यकीय नोंदणी क्रमांक',
    'auth.address': 'रुग्णालयाचा संपूर्ण पत्ता',
    'auth.contact_person': 'वैद्यकीय अधीक्षक / संपर्क व्यक्ती',
    'auth.submit_signin': 'खात्यात साइन इन करा',
    'auth.submit_register': 'नोंदणी पूर्ण करा',

    // Common
    'common.language': 'भाषा',
    'common.english': 'English',
    'common.hindi': 'हिन्दी',
    'common.marathi': 'मराठी',
    'common.mumbai': 'मुंबई',
    'common.pune': 'पुणे',
    'common.nagpur': 'नागपूर',
    'common.government': 'शासकीय',
    'common.private': 'खाजगी',
    'common.rating': 'दर्जा',
    'common.available': 'उपलब्ध',
    'common.occupied': 'भरलेले',
    'common.minutes': 'मिनिटे',
    'common.km': 'किमी',

    // Hospital Dashboard
    'hospital.dashboard_title': 'रुग्णालय पोर्टल',
    'hospital.active_requests': 'सक्रिय मागण्या',
    'hospital.fulfilled_month': 'या महिन्यात पूर्ण',
    'hospital.avg_match_time': 'सरासरी जुळणी वेळ',
    'hospital.donor_pool_size': 'शहरातील दात्यांची संख्या',
    'hospital.create_emergency': 'आपत्कालीन मागणी नोंदवा',
    'hospital.trigger_matching': 'दाता जुळणी इंजिन सुरू करा',
    'hospital.trigger_matching_desc': 'तातडीची रक्त/अवयव सुसंगतता शोध प्रणाली सुरू करा',
    'hospital.connect_donors': 'दात्यांशी संपर्क साधा',
    'hospital.connect_donors_desc': 'उपलब्ध रक्त आणि नोंदणीकृत अवयवदात्यांची यादी पहा',
    'hospital.search_stock': 'जवळच्या रुग्णालयातील साठा शोधा',
    'hospital.search_stock_desc': 'इतर रुग्णालयांकडून तातडीचे रक्त किंवा अवयव हस्तांतरण मागा',
    'hospital.active_past_requests': 'सक्रिय व मागील आपत्कालीन मागण्या',
    'hospital.requests_subtitle': 'थेट जुळणी इंजिन व पाठवणी नियंत्रणासह थेट स्थिती ट्रॅकिंग',
    'hospital.type': 'प्रकार',
    'hospital.required_item': 'आवश्यक घटक',
    'hospital.urgency': 'तातडी',
    'hospital.city': 'शहर',
    'hospital.match_score': 'मॅच स्कोअर',
    'hospital.status': 'स्थिती',
    'hospital.action': 'कृती',
    'hospital.match_now': 'आत्ताच मॅच करा',
    'hospital.track_dispatch': 'पाठवणी ट्रॅक करा',
    'hospital.hash_log': 'सुरक्षित हॅश नोंद',
    'hospital.verified': 'प्रमाणित',
    'hospital.license': 'नोंदणी क्रमांक',
    'hospital.emergency_alert_title': '🚨 अत्यंत गंभीर अपघात आपत्कालीन अलर्ट',
    'hospital.emergency_alert_sub': 'अपघातातील जखमी रुग्ण रुग्णालयाकडे रवाना झाले आहेत. तात्काळ ट्रॉमा वॉर्ड सज्ज करा.',
    'hospital.patients_allocated': 'वाटप केलेले रुग्ण',
    'hospital.eta': 'अंदाजे पोहोचण्याची वेळ',
    'hospital.acknowledge': 'स्वीकारा व ट्रॉमा वॉर्ड सज्ज करा',
    'hospital.mark_arrived': 'रुग्ण पोहोचले (नोंद पूर्ण करा)',

    // Donor Dashboard
    'donor.portal': 'सक्रिय दाता पोर्टल',
    'donor.welcome': 'पुन्हा स्वागत आहे',
    'donor.subtitle': 'तुमचे जीवनरक्षक योगदान, शहरातील मानांकन आणि आपत्कालीन तयारी पहा.',
    'donor.tab_overview': 'प्रभाव आढावा',
    'donor.tab_leaderboard': 'शहर मानांकन',
    'donor.tab_notifications': 'मॅच फीड',
    'donor.blood_group': 'रक्त गट',
    'donor.city_zone': 'शहर क्षेत्र',
    'donor.pledged_organs': 'संकल्पित अवयव',
    'donor.blood_donations': 'रक्तदान संख्या',
    'donor.phone': 'फोन',
    'donor.availability': 'आपत्कालीन उपलब्धता',
    'donor.availability_ready': 'आपत्कालीन अलर्टसाठी सज्ज',
    'donor.availability_paused': 'तात्पुरते थांबवले',
    'donor.pledge_organs_action': 'अवयवदान संकल्प करा',
    'donor.pledge_organs_desc': 'दान करण्यासाठी अवयव निवडा (+६० गुण)',
    'donor.log_donation_action': 'रक्तदानाची नोंद करा',
    'donor.log_donation_desc': 'केलेले रक्तदान नोंदवा (+३० गुण)',
    'donor.progression': 'जीवनरक्षक वाटचाल',
    'donor.lifetime_points': 'एकूण जीवनरक्षक गुण',
    'donor.badges_title': 'मिळालेले व पुढील बॅजेस',
    'donor.badges_desc': 'नियमित रक्तदान व अवयवदान करून विशेष गौरव मिळवा',
    'donor.total_points': 'एकूण गुण',
    'donor.donations': 'दाने',
    'donor.organs_pledged': 'संकल्पित अवयव',
    'donor.top_donors': 'शीर्ष दाते',
    'donor.leaderboard_desc': 'रक्तदान वारंवारता आणि संकल्पावर आधारित थेट मानांकन',
    'donor.alerts_title': 'अलर्ट व जुळणी इतिहास',
    'donor.alerts_desc': 'आपले रक्त किंवा अवयव रुग्णालयाच्या मागणीशी जुळल्यास तात्काळ अलर्ट',
    'donor.no_alerts': 'सध्या कोणतेही अलर्ट नाहीत',

    // Multi-Patient Emergency Allocation
    'emergency.num_patients': 'अपघातग्रस्त जखमी / रुग्णांची संख्या',
    'emergency.num_patients_hint': 'खाटा भरल्यास आपोआप जवळच्या रुग्णालयांमध्ये रुग्ण विभागले जातात',
    'emergency.allocation_title': 'रुग्ण खाटा वाटप व रुग्णवाहिका पाठवणी',
    'emergency.primary_hosp': 'प्राथमिक रुग्णालय (थेट ट्रॉमा वॉर्ड)',
    'emergency.secondary_hosp': 'जवळचे दुय्यम रुग्णालय (खाटा मर्यादा पुनर्निर्देशन)',
    'emergency.patients_count': 'रुग्ण',
    'emergency.reroute_notice': 'प्राथमिक रुग्णालयातील ट्रॉमा खाटा पूर्ण झाल्याने उर्वरित रुग्ण आपोआप जवळच्या दुसऱ्या रुग्णालयाकडे पाठवण्यात आले आहेत.',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('aarogyam_lang') as Language;
    return saved && (saved === 'en' || saved === 'hi' || saved === 'mr') ? saved : 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('aarogyam_lang', lang);
  };

  const t = (key: string): string => {
    return translations[language]?.[key] || translations['en']?.[key] || key;
  };

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
